<h2>Se connecter avec un compte utilisateur</h2>
<form method="POST" class="generic-form">
<fieldset>
        <legend>Inforamtions d'authentification</legend>
        <div>
            <label for="mail">E-mail :</label>
            <input type='email' name='mail' id='mail'>
        </div>
        <div>
            <label for="password">Mot de passe :</label>
            <input type='password' name='password' id='password'>
        </div>
    </fieldset>
    <button class="button button-primary" type="submit">Se connecter</button>
    <button class="button button-cancel" type="reset"><a href="<?= $requestUrl ?>">Annuler</a></button>
    </form>