
<h2><i class="fas fa-user-alt"></i> Création d'un compte client</h2>

<form method="POST" class="generic-form">
    <fieldset>
        <legend>Identité et coordonnées</legend>
        <div>
            <label for="firstName">Prénom :</label>
            <input type='text' name='firstName' id='firstName' value="<?= $formFields['firstName'] ?>">
        </div>
        <div>
            <label for="lastName">Nom :</label>
            <input type='text' name='lastName' id='lastName' value="<?= $formFields['lastName'] ?>">
        </div>
        <div>
            <label for="BirthDate">Date de naissance :</label>
            <input type="date" name="BirthDate" id="BirthDate" value="<?= $formFields['BirthDate'] ?>">    
        </div>
        <div>
            <label for="adress">Adresse :</label>
            <input type='text' name='adress' id='adress' value="<?= $formFields['adress'] ?>">
        </div>
        <div>
            <label for="city">ville:</label>
            <input type='text' name='city' id='city' value="<?= $formFields['city'] ?>">
        </div>
        <div>
            <label for="postalCode">Code postal :</label>
            <input type='text' name='postalCode' id='postalCode' value="<?= $formFields['postalCode'] ?>">
        </div>
        <div>
            <label for="country">Pays :</label>
            <input type='text' name='country' id='country' value="<?= $formFields['country'] ?>">
        </div>
        <div>
            <label for="phone">Téléphone :</label>
            <input type='tel' name='phone' id='phone' value="<?= $formFields['phone'] ?>">
        </div>
    </fieldset>
    <fieldset>
        <legend>Inforamtions d'authentification</legend>
        <div>
            <label for="mail">E-mail :</label>
            <input type='email' name='mail' id='mail' value="<?= $formFields['mail'] ?>">
        </div>
        <div>
            <label for="password">Mot de passe :</label>
            <input type='password' name='password' id='password' value="<?= $formFields['password'] ?>">
            
        </div>
    </fieldset>
    <?php 
        if(isset($errors) && count($errors) > 0){
            foreach($errors as $error){
                echo '<p>'.$error.'</p>';
            }
        }
    ?>
    <button class="button button-primary" type="submit">Créer un compte</button>
    <button class="button button-cancel" type="reset"><a href="<?= $requestUrl ?>">Annuler</a></button>
</form>