<nav class="user-interface">
<ul class="link-list">
<?php if(isset($_SESSION['user'])): ?>
    <li class="btnConnect">Bonjour <?= $_SESSION['user']['FirstName'] . ' ' . $_SESSION['user']['LastName']; ?></li>
    <li><button class="button button-primary"><a href="<?= $requestUrl ?>/">Meal</a></button></li>
    <li><button class="button button-primary"><a href="<?= $requestUrl ?>/Order">Commander</a></button></li>
    <li><button class="button button-cancel" type='submit' name='loginOut'><a href="<?= $requestUrl ?>/LoginOut">Décoonxion</a></button></li>
    <?php endif; ?>
</ul>
</nav>
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <!-- Code HTML à écrire -->
        
        <?php  foreach($meals as $mil) : ?>
        
            <tr>
                <td><img src="<?= $wwwUrl ?>/images/meals/<?= $mil['Photo']; ?>" alt='burger'></td>
                
                <td><strong><?= $mil['Name'].'</strong><br>'.$mil['Description']; ?></td>
                <td><?= $mil['SalePrice']; ?> €</td>
            </tr>          
                
        <?php endforeach; ?>
    </tbody>
</table>