<h2>Paneau d'administration</h2>
<form method='POST'>
    <fieldset>
    <legend>Historique des commandes</legend>
    <table>
        <thead>
            <tr>
                <th>Num Com</th>
                <th>Num User</th>
                <th>Date Création</th>
                <th>Date Succ</th>
                <th>tva</th>
                <th>Prix tva</th>
                <th>totla</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($orders as $order) : ?>
                <tr>
                    <td><a href="DetailsOrder?id='.$order['Order_Id'].'"><?= $order['Id'] ?></a></td>
                    <td><?= $order['User_Id'] ?></td>
                    <td><?= $order['CreationTimestamp'] ?></td>
                    <td><? $order['CompleteTimestamp'] ?></td>
                    <td><?= $order['TaxAmount'] ?></td>
                    <td><?= $order['TaxRate'] ?></td>
                    <td><?= $order['TotalAmount'] ?></td>
                </tr>
            
             <?php endforeach; ?>
        </tbody>
    </table>
    </fieldset>
    
</form>
<form>
    <fieldset>
            <legend>Détails</legend>
            
    </fieldset>
</form>